apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rekor
    repo: https://sigstore.github.io/helm-charts
    version: 1.3.7
    releaseName: rekor
    namespace: rekor-system
    valuesFile: values.yaml

resources:
  - rolebinding.yaml
  - route.yaml
